name: 'CustomDiscs'
version: '$version'
main: 'io.github.subkek.customdiscs.CustomDiscs'
api-version: '1.16'
authors: [ 'sub-kek' ]
description: 'Custom discs for SVC by sub-kek.'
depend: [ 'voicechat', 'ProtocolLib' ]
folia-supported: true
commands:
  customdisc:
    description: The custom discs command.
    aliases: cd
permissions:
  customdiscs.*:
    children:
      customdiscs.download: true
      customdiscs.create: true
      customdiscs.createyt: true
      customdiscs.reload: true
      customdiscs.playt: true
      customdiscs.play: true
      customdiscs.help: true
  customdiscs.download:
    default: op
  customdiscs.create:
    default: op
  customdiscs.createyt:
    default: op
  customdiscs.reload:
    default: op
  customdiscs.playt:
    default: op
  customdiscs.play:
    default: op
  customdiscs.help:
    default: op