name: Customdiscs CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set up JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: temurin
          java-version: 21
      - name: Build CustomDiscs
        run: ./gradlew build
      - name: Upload CustomDiscs
        uses: actions/upload-artifact@v4
        with:
          name: "CustomDiscs"
          path: "build/libs/"
